name: 'dbt_users_activity'
version: '1.0.0'
config-version: 2

profile: 'dbt_users_activity'

model-paths: ["models"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_users_activity:
    +materialized: table