dbt_users_activity:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: your-project-id
      dataset: your_dataset
      keyfile: path/to/your-service-account.json
      threads: 1